"""Added orders2

Revision ID: 37161da052d0
Revises: 46215c561db7
Create Date: 2022-05-15 13:30:11.858642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37161da052d0'
down_revision = '46215c561db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('ship_address', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_details',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('orders')
    # ### end Alembic commands ###
