"""Kill me please

Revision ID: 38e1f655dfa4
Revises: beb80da76ed1
Create Date: 2022-06-06 20:36:54.933269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e1f655dfa4'
down_revision = 'beb80da76ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.VARCHAR(length=45), nullable=True))
    op.drop_column('orders', 'adress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('adress', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
