"""Changed password length

Revision ID: 3a0b85f1689e
Revises: 6dec0113dd69
Create Date: 2022-06-03 12:51:11.815602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0b85f1689e'
down_revision = '6dec0113dd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
