"""Added orders

Revision ID: 46215c561db7
Revises: 5df8be27844e
Create Date: 2022-05-15 13:24:09.989134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46215c561db7'
down_revision = '5df8be27844e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zip', sa.VARCHAR(length=45), nullable=True))
    op.add_column('users', sa.Column('adress', sa.VARCHAR(length=45), nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=45), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_column('users', 'city')
    op.drop_column('users', 'adress')
    op.drop_column('users', 'zip')
    # ### end Alembic commands ###
