"""Added is superuser column

Revision ID: 6dec0113dd69
Revises: eccea85fbbfb
Create Date: 2022-06-03 11:35:16.621309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dec0113dd69'
down_revision = 'eccea85fbbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=45), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
