"""Changed password again

Revision ID: c611033e3a1c
Revises: 3a0b85f1689e
Create Date: 2022-06-03 12:51:53.406451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c611033e3a1c'
down_revision = '3a0b85f1689e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
