"""Added address to order

Revision ID: eccea85fbbfb
Revises: 37161da052d0
Create Date: 2022-06-03 11:24:56.024234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eccea85fbbfb'
down_revision = '37161da052d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('orders', sa.Column('city', sa.VARCHAR(length=45), nullable=True))
    op.add_column('orders', sa.Column('zip', sa.VARCHAR(length=45), nullable=True))
    op.add_column('orders', sa.Column('adress', sa.VARCHAR(length=45), nullable=True))
    op.drop_column('orders', 'ship_address')
    op.drop_column('orders', 'create_at')
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=45), nullable=True))
    op.add_column('users', sa.Column('sex', sa.VARCHAR(length=45), nullable=True))
    op.drop_column('users', 'adress')
    op.drop_column('users', 'city')
    op.drop_column('users', 'zip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zip', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('adress', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_column('users', 'sex')
    op.drop_column('users', 'password')
    op.add_column('orders', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('ship_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('orders', 'adress')
    op.drop_column('orders', 'zip')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
